version: "3"

services:
  jupyter:
    image: jupyter-vim:latest
    ports:
      - 8888:8888
    volumes:
      - project_data:/project_data
    user: root
    environment:
      JUPYTER_TOKEN: "docker"
      NB_USER: docker_worker
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
volumes:
  project_data:
